git: fix pull request deletion - don't crash on deleting refs to PR heads
The refs name was passed as unicode string, and that would cause failure like:
  File ".../site-packages/dulwich/repo.py", line 720, in __delitem__
    if name.startswith(b"refs/") or name == b"HEAD":
  TypeError: startswith first arg must be str or a tuple of str, not bytes

Fixed by correctly passing the ref name as bytes, as we do when creating the PR
refs.

Tests added by Mads Kiilerich.