setup: bump WebOb minimum version to 1.8
b075693b3214 introduced use of acceptable_offers which with WebOb < 1.8 would
fail with:

  File ".../kallithea/lib/middleware/pygrack.py", line 189, in __call__
    elif req.accept.acceptable_offers(self.valid_accepts):
AttributeError: 'MIMEAccept' object has no attribute 'acceptable_offers'