diff: fix two-way diff for added or removed files
Viewing the two-way diff of an added file gives following exception:

      File "_base_root_html", line 211, in render_body

      File "_base_base_html", line 42, in render_body

      File "files_diff_2way_html", line 197, in render_main

      File ".../kallithea/lib/vcs/nodes.py", line 411, in is_binary
        return b'\0' in self.content
    TypeError: 'in <string>' requires string as left operand, not bytes

At this point, self.content was '' (empty string).

Commit 9203621cae03a03bbf8cfb4b667daa656780a93e made that node content is
always bytes, but this also had to be reflected in EmptyChangeset.

Add a basic test that catches this behavior.