tg: fix launching with kajiki after moving to FullStackApplicationConfigurator 27d9ca0c8381
Application start failed with:
    TypeError: 'FullStackApplicationConfigurator' object is not subscriptable