vcs: fix repo creation with a remote clone uri under Python 3
When trying to add a new repository based on a remote clone, it fails in
Python 3 as follows, for git:

ERROR    kallithea.model.validators:validators.py:413 URL validation failed
Traceback (most recent call last):
  File ".../kallithea/model/validators.py", line 411, in _validate_python
    is_valid_repo_uri(repo_type, url, make_ui())
  File ".../kallithea/lib/utils.py", line 250, in is_valid_repo_uri
    GitRepository._check_url(url)
  File ".../kallithea/lib/vcs/backends/git/repository.py", line 174, in _check_url
    if not test_uri.endswith('info/refs'):
TypeError: endswith first arg must be bytes or a tuple of bytes, not str

and for hg, the other way around:

ERROR    kallithea.model.validators:validators.py:413 URL validation failed
Traceback (most recent call last):
  File ".../kallithea/model/validators.py", line 411, in _validate_python
    is_valid_repo_uri(repo_type, url, make_ui())
  File ".../kallithea/lib/utils.py", line 233, in is_valid_repo_uri
    MercurialRepository._check_url(url, ui)
  File ".../kallithea/lib/vcs/backends/hg/repository.py", line 297, in _check_url
    if os.path.isdir(url) or url.startswith(b'file:'):
TypeError: startswith first arg must be str or a tuple of str, not bytes

In both cases, the code seems to actually expect a bytes url.