i18n: pt_BR: fix empty 'Language' entry
This causes 'python2 setup.py update_catalog' to fail with:

      File "/usr/lib64/python2.7/site-packages/babel/core.py", line 1094, in parse_locale
        raise ValueError('expected only letters, got %r' % lang)
    ValueError: expected only letters, got u''